### ISSUE TITLE
I am having trouble installing this with composer

### ISSUE THREAD

**Issue by Mandeepsinghatintricare** [DantSu/php-image-editor#1]
I am getting these exceptions while installing them

 

> Package dantsu/php-image-editor has requirements incompatible with your PHP version, PHP extensions and Composer version:

>    - dantsu/php-image-editor 1.0.3 requires php ^7.0 which does not match your installed version 8.1.4.

>    - dantsu/php-image-editor 1.0.3 requires ext-gd * but it is not present.

Help how can I solve these

**Comment by DantSu** [comment]
Pls try again and give me a feedback

**Comment by Mandeepsinghatintricare** [comment]
Same thing is happening again
![image](https://user-images.githubusercontent.com/103239172/167634960-298aa5a7-6122-4828-a0c7-825c12e73b52.png)

**Comment by DantSu** [comment]
Remaining only GD extension missing.
You have to install GD extension with PHP : https://www.php.net/manual/en/book.image.php

**Comment by Mandeepsinghatintricare** [comment]
Thanks for helping out the issue has been solved
