### ISSUE TITLE
bag: imagejpeg() expects at most 3 arguments, 4 given

### ISSUE THREAD

**Issue by dmalapsh** [DantSu/php-image-editor#3]
The getData JPG method passes imagejpeg to the getData method. getdate, in turn, runs the imagejpeg function with 4 parameters, but it expects only 3
https://github.com/DantSu/php-image-editor/blob/98985faea4ace4fef932698b9f9a359f9fca8787/src/Image.php#L1218
https://www.php.net/manual/en/function.imagejpeg.php

**Comment by DantSu** [comment]
I send only 3 arguments to imagejpeg. How did you do to have this error ?

**Comment by dmalapsh** [comment]
I attached a link to the code in the first message. There are 4 arguments passed: 1)$this->image, 2) null, 3)$quality, 4)-1.

**Comment by DantSu** [comment]
Ok link to the line dont works on github android app. Try v1.2.0 and give me a feedback.

**Comment by dmalapsh** [comment]
Problem solved
